baseURL = "/"
locale = "sv-SE"
defaultContentLanguage = "sv"
title = "Equilo"
themesDir = "themes"
theme = "hugo-hero-theme"
publishdir="docs"

[params]
  google_analytics_id="UA-23148826-2"

  [params.homepage_meta_tags]
    meta_description = "Equilo – begravningsrådgivning, boutredning och arvskifte."
    meta_og_title = "Equilo"
    meta_og_type = "website"
    meta_og_url = "https://equilo.se"
    meta_og_image = ""
    meta_og_description = "Equilo – begravningsrådgivning, boutredning och arvskifte."

[[menu.main]]
    identifier = "funeral-advisory"
    name = "Begravningsrådgivning"
    url = "/begravningsradgivning/"
    weight = 1

[[menu.main]]
    identifier = "estate-inventory"
    name = "Boutredning"
    url = "/boutredning/"
    weight = 2

[[menu.main]]
    identifier = "estate-distribution"
    name = "Arvskifte"
    url = "/arvskifte/"
    weight = 3

[[menu.main]]
    identifier = "other-services"
    name = "Övriga tjänster"
    url = "/ovriga-tjanster/"
    weight = 4

[[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
